### ISSUE TITLE
Multiline flag doesn't seem to work

### ISSUE THREAD

**Issue by balupton** [greymd/teip#28]
I'm assuming this uses the rust regex engine:

https://docs.rs/regex/latest/regex/#grouping-and-flags

Of which the following should work right?

``` bash
echo $'a\nb\nc\na\nb\nc' | teip -g '(?m:\nb$)'
```

Such that I can do:

``` bash
echo $'a\nb\nc\na\nb\nc' | teip -g '(?m:\nb$)' -- sd '.*' ''
```

to get back:

```
a
c
a
c
```

As such works with [sd](https://github.com/chmln/sd)

``` bash
echo $'a\nb\nc\na\nb\nc' | sd '(?m:\nb$)' ''
```

**Comment by greymd** [comment]
This is the expected behavior.
Unfortunately, I have no plans to support the behavior in the future.

If you hope to match with multi-line mode, please use the `-z` option like this.

```sh
$ echo $'a\nb\nc\na\nb\nc' | teip -z -g '\nb' -o
a[
b]
c
a[
b]
c
```

Let me explain the technical background.
`teip` can give only the matched parts to another command.
In this case, each occurence is concatenated with a newline and given as standard input.
Therefore, if the single occurence contains newlines, it will cause unexpected behavior, so the flag is set to [a fixed value](https://github.com/greymd/teip/blob/c1d25d85c17072ed68a4e5ec367e8184b725d033/src/main.rs#L389).

When the `-z` option is used, the NUL character is used as the concatination character, so it is controlled to avoid problems (see [README](https://github.com/greymd/teip#nul-as-line-delimiter) for detailed behavior).
