### ISSUE TITLE
FR: man page

### ISSUE THREAD

**Issue by nkh** [greymd/teip#59]
It seems that rust folk are allergic to man pages, which is weird because those who are on linux use them all the time. I do understand that it's a linux thing and that writing portable code mean portable documentation but IMVH it's a mistake to not integrate in the man page system; some users will also fine tune their man page system to be more "efficient", I do).

There's also the false impression that creating man pages is tedious, well it can be, but modern solutions exist like converting and installing a markdown file.

Since I plan to use teip more I created one (I do it for my modules when the build system doesn't https://github.com/nkh/ftl/blob/main/config/ftl/man/gen_man_pages)

Screenshot of me searching for solid in your manpage (it's not a default setup but normal man setup will work fine too)

![screenshot_2023-09-01_10-08-06](https://github.com/greymd/teip/assets/45409/b8e503eb-bc2e-4f5b-af5d-74045aa80eb8)

**Comment by greymd** [comment]
Sorry for the late response.

As a Linux user myself, I frequently use man pages, so I understand your point of view.

In case you're not aware, teip already has man pages prepared.
https://github.com/greymd/teip/blob/main/man/man.md

Additionally, when installing via rpm or deb packages, or homebrew, the man pages are also installed.
https://github.com/greymd/teip/blob/9fc3f1478aec1822cf66ebd9ab3e5cce848b6cee/.github/workflows/release.yml#L193

Therefore, I believe that the request in this Issue is currently being met. Please let me know if there is any misunderstanding on my part.

However, I feel that maintaining both the current README.md and the man pages is a bit troublesome (since man pages are intended for terminal viewing, I don't think it's appropriate to directly convert the README.md content). If you have any ideas on how to manage this duplication more effectively, I would appreciate your cooperation :)

I will close this Issue for now.
